### ISSUE TITLE
Design Improvements

### ISSUE THREAD

**Issue by flywheel-jack** [n8finch/local-site-search-addon#1]
**Is your feature request related to a problem? Please describe.**
Improve readability and user flow of search on connected sites list

**Describe the solution you'd like**
Move search field to the far right of navtabs (remove :before hook)
Vertically align icon w/ placeholder text

**Additional context**
<img width="1342" alt="Screen Shot 2019-04-24 at 4 19 00 PM" src="https://user-images.githubusercontent.com/47259147/56694830-3a008a00-66ad-11e9-9897-efe05c81d1b4.png">

**Comment by adamtrabold** [comment]
This is looking great! In addition to moving the search field to the right edge, it would be awesome to have a headline appear above the sites that says "Searching for '[search term here]'." Just an idea – did a quick sketch!

![IMG_5290](https://user-images.githubusercontent.com/3850045/56695017-b85d2c00-66ad-11e9-8369-adcac25ef543.jpg)

**Comment by n8finch** [comment]
Hey @flywheel-jack and @adamtrabold , thanks for the issue!

I've updated the master branch with the changes, so feel free to pull that down and let me know how it goes.

I've tested on three versions of Local (on Mac), and I'm wondering if y'all have any insight into the Hooks and Filters situation. I'm using the following hooks (withe the type noted):

- SitesSidebar_SitesSidebarSites:Before (content)
- SitesSidebar_SitesSidebarSites (content)
- FlywheelConnectSites_availableSites (filter)
- FlywheelConnectSites_TabNav (content, it might be nice to have a priority parameter for this eventually too, so I make sure most everything else comes before the search input, but that can come later 🤓)
- FlywheelConnectSites_FlywheelSitesList:Before (content)

Are these hooks in the most recent Teams version?

**Versions tested:**
- Teams (downloaded this afternoon): v.3.1.2: doesn't show up with the add-on is activated, assuming that the hooks and filters aren't in this one, maybe?
- Dev (zip from Clay): v.3.1.2: Works just fine...
- Standard version (available for download [here](https://localbyflywheel.com/)): 3.0.4: Doesn't show up, assuming that the hooks and filters aren't in this one either.

Anything else let me know.

Cheers!

**Comment by n8finch** [comment]
@flywheel-jack Thanks for the PR, I commented out the dev helpers and went ahead and merged it. I like the design additions! Thanks for doing that!

Things worked on that Dev version of Local, but not my current version of Local (for Teams, v3.1.2). Do you know if those hooks and filters are going into the next version of Teams?

Cheers!

**Comment by flywheel-jack** [comment]
Fab! To confirm, you couldn’t get this version to work? I’m running an unreleased beta, so I’m wondering if that’s why?

**Comment by n8finch** [comment]
@flywheel-jack hahaa, yeah, I _could_ get it to work on that unreleased Beta (I think that we're working off the same thing), but not on the current version I have with Teams (v.3.1.2), or the Standard version (available for download [here](https://localbyflywheel.com/)): v3.0.4. Make sense? 😄

**Comment by n8finch** [comment]
_Closing for now, feel free to reopen for discussion _ 😄.
